In [19]:
import numpy as np
from scipy import stats
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [13]:
df =pd.read_csv("mapeRMSER2.csv")

df1 = df[df['Climatico'] == "Diario"]

df1.head()

    Climatico   ML  Precicion    MAPE     RMSE       t/h     kg/h      R2
8      Diario   RF     0.9619  0.0381  35.7214  0.357214  357.214  0.8675
40     Diario  XGB     0.9574  0.0426  40.9659  0.409659  409.659  0.8258
151    Diario  SVR     0.9191  0.0809  61.6549  0.616549  616.549  0.6053

In [11]:
df2 = df[df['Climatico'] == "Mensual"]

df2.head()

    Climatico   ML  Precicion    MAPE     RMSE       t/h     kg/h      R2
9     Mensual   RF     0.9619  0.0381  35.8191  0.358191  358.191  0.8668
43    Mensual  XGB     0.9574  0.0426  40.9659  0.409659  409.659  0.8258
162   Mensual  SVR     0.9177  0.0823  63.1830  0.631830  631.830  0.5855

In [17]:
group1 = df1["MAPE"].values
group2 = df2["MAPE"].values

t_statistic, p_value = stats.ttest_ind(group1, group2, equal_var=True)

# Imprimir los resultados
print("Estadístico t:", t_statistic)
print("Valor p:", p_value)

# Interpretar los resultados
alpha = 0.05
if p_value < alpha:
    print("Rechazamos la hipótesis nula. Hay una diferencia significativa entre las medias.")
else:
    print("No podemos rechazar la hipótesis nula. No hay evidencia suficiente para concluir que hay una diferencia significativa.")

Estadístico t: -0.023888976313432574
Valor p: 0.982085397607928
No podemos rechazar la hipótesis nula. No hay evidencia suficiente para concluir que hay una diferencia significativa.

In [20]:
# Crear un DataFrame de ejemplo
data = {'grupo': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'],
        'valor': [10, 12, 14, 8, 9, 11, 15, 17, 19]}
df = pd.DataFrame(data)

# Modelo ANOVA
model = ols('valor ~ grupo', data=df).fit()

# Resumen del modelo
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

             sum_sq   df          F    PR(>F)
grupo     90.888889  2.0  13.193548  0.006358
Residual  20.666667  6.0        NaN       NaN