# Create a new dataset and run it on all machines

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
module_path = os.path.abspath(os.path.join('../../'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
import pandas as pd

In [4]:
file_csv = '../../data/obregon_1516_1617/original/o_57_o_phenotypic.csv'
df = pd.read_csv(file_csv, header=0)
df.head()

,TGW,HI,BM,NDVI_VG1,NDVI_VG2,NDVI_VG3,NDVI_VG4,NDVI_VG,NDVI_GF1,NDVI_GF2,...,NDVI_UAV_1,NDVI_UAV_2,NDVI_UAV_3,NDVI_UAV_4,NDVI_UAV_5,CT_UAV_1,CT_UAV_2,CT_UAV_3,CT_UAV_4,YLD
0,40.510542,0.493706,1252.841830,0.171286,0.176257,0.375381,0.757965,0.444839,0.776698,0.744168,...,0.499727,0.458816,0.659201,0.754407,0.873936,25.451605,24.184386,24.083716,31.700124,617.4453
1,37.094174,0.492329,1403.919849,0.170764,0.214652,0.409778,0.782313,0.469060,0.770800,0.720762,...,0.486031,0.499782,0.693321,0.777470,0.878137,25.482403,24.005464,23.580308,31.270182,689.6464
2,44.201750,0.498393,1376.809117,0.156686,0.169272,0.334773,0.738150,0.417022,0.751064,0.667258,...,0.462325,0.431861,0.610026,0.708450,0.875478,25.643851,24.291071,24.444127,32.008681,687.2559
3,32.876596,0.516203,1234.698326,0.165603,0.190059,0.332481,0.675919,0.406757,0.728636,0.643564,...,0.413157,0.405293,0.560463,0.652515,0.844511,26.120276,24.171371,25.492758,34.282378,636.4969
4,41.374175,0.481962,1279.299001,0.187345,0.221703,0.429379,0.778879,0.472912,0.755801,0.731699,...,0.492748,0.494245,0.653331,0.738558,0.882129,25.619695,23.807970,23.970900,31.579817,616.5022

In [5]:
column_not_ndvi = []
for column in df.columns:
    if not "NDVI" in column:
        column_not_ndvi.append(column)

print(column_not_ndvi)

['TGW', 'HI', 'BM', 'CT_UAV_1', 'CT_UAV_2', 'CT_UAV_3', 'CT_UAV_4', 'YLD']

In [6]:
df_no_ndvi = df[column_not_ndvi]

df_no_ndvi.head()

,TGW,HI,BM,CT_UAV_1,CT_UAV_2,CT_UAV_3,CT_UAV_4,YLD
0,40.510542,0.493706,1252.841830,25.451605,24.184386,24.083716,31.700124,617.4453
1,37.094174,0.492329,1403.919849,25.482403,24.005464,23.580308,31.270182,689.6464
2,44.201750,0.498393,1376.809117,25.643851,24.291071,24.444127,32.008681,687.2559
3,32.876596,0.516203,1234.698326,26.120276,24.171371,25.492758,34.282378,636.4969
4,41.374175,0.481962,1279.299001,25.619695,23.807970,23.970900,31.579817,616.5022

In [7]:
df_no_ndvi.to_csv('../../data/obregon_1516_1617/original/o_57_o_phenotypic_no_ndvi.csv', index=False)